[package]
name = "boilermaker_web"
version = "0.1.0"
edition = "2021"

[dependencies]
# Internal
boilermaker_api = { workspace = true }
boilermaker_core = { workspace = true }
boilermaker_ui = { workspace = true }
# External
axum = { workspace = true }
axum-embed = { workspace = true }
axum-template = { workspace = true }
color-eyre = { workspace = true }
dioxus = { workspace = true }
minijinja = { workspace = true }
minijinja-autoreload = { workspace = true }
pulldown-cmark = { workspace = true }
regex = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
