[workspace]
resolver = "2"
members = ["api", "boil", "examples/hello-world", "util", "web"]

[workspace.dependencies]
clap = { version = "4.5.47", features = ["derive"] }
color-eyre = "0.6.5"
dioxus = { version = "0.6.3" }
dirs = "6.0.0"
gitoxide = "0.45.0"
indoc = "2.0.6"
lazy_static = "1.5.0"
nu-ansi-term = "0.50.1"
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
toml = "0.9.5"
tracing = { version = "0.1.41", features = ["log"] }
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.20", features = [
    "json",
    "registry",
    "env-filter",
] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }

# workspace
api = { path = "api" }
util = { path = "util" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
