[package]
name = "boilermaker_views"
version = "0.1.0"
edition = "2024"

[dependencies]

# External
dioxus = { workspace = true, features = ["router"] }
indoc = { workspace = true }

# Internal
boilermaker_core = { workspace = true }
