[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]

# External
async-trait = { workspace = true }
color-eyre = { workspace = true }
sqlx = { workspace = true }
tabled = { workspace = true }
tracing = { workspace = true }

# Internal
util = { workspace = true }
